on:
  release:
    types: [created]

# Permissionは必ず付ける
permissions:
  contents: write

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos:
          linux:
            goarch: [amd64, arm64, riscv64]
          windows:
            goarch: [amd64, arm64]
          darwin:
            goarch: [amd64, arm64]
    steps:
      - uses: actions/checkout@v3
      - uses: wangyoucao577/go-release-action@v1
        with:
          # トークンは別途用意しなくてよい
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goversion: "https://dl.google.com/go/go1.22.5.linux-amd64.tar.gz"
          project_path: "."
          binary_name: "hello"
